// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: saga/v1/events.proto

package sagav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SagaEvent is the envelope for all Kafka messages in the saga flow.
type SagaEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SagaEvent) Reset() {
	*x = SagaEvent{}
	mi := &file_saga_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SagaEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaEvent) ProtoMessage() {}

func (x *SagaEvent) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaEvent.ProtoReflect.Descriptor instead.
func (*SagaEvent) Descriptor() ([]byte, []int) {
	return file_saga_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *SagaEvent) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *SagaEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SagaEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SagaEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type OrderCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreatedEvent) Reset() {
	*x = OrderCreatedEvent{}
	mi := &file_saga_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatedEvent) ProtoMessage() {}

func (x *OrderCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatedEvent.ProtoReflect.Descriptor instead.
func (*OrderCreatedEvent) Descriptor() ([]byte, []int) {
	return file_saga_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *OrderCreatedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCreatedEvent) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderCreatedEvent) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_saga_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_saga_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *OrderItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type InventoryReserveCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReserveCommand) Reset() {
	*x = InventoryReserveCommand{}
	mi := &file_saga_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReserveCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReserveCommand) ProtoMessage() {}

func (x *InventoryReserveCommand) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReserveCommand.ProtoReflect.Descriptor instead.
func (*InventoryReserveCommand) Descriptor() ([]byte, []int) {
	return file_saga_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *InventoryReserveCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *InventoryReserveCommand) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type InventoryReservedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReservedEvent) Reset() {
	*x = InventoryReservedEvent{}
	mi := &file_saga_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReservedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReservedEvent) ProtoMessage() {}

func (x *InventoryReservedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReservedEvent.ProtoReflect.Descriptor instead.
func (*InventoryReservedEvent) Descriptor() ([]byte, []int) {
	return file_saga_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *InventoryReservedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type InventoryFailedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryFailedEvent) Reset() {
	*x = InventoryFailedEvent{}
	mi := &file_saga_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryFailedEvent) ProtoMessage() {}

func (x *InventoryFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryFailedEvent.ProtoReflect.Descriptor instead.
func (*InventoryFailedEvent) Descriptor() ([]byte, []int) {
	return file_saga_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *InventoryFailedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *InventoryFailedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type InventoryReleaseCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReleaseCommand) Reset() {
	*x = InventoryReleaseCommand{}
	mi := &file_saga_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReleaseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReleaseCommand) ProtoMessage() {}

func (x *InventoryReleaseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReleaseCommand.ProtoReflect.Descriptor instead.
func (*InventoryReleaseCommand) Descriptor() ([]byte, []int) {
	return file_saga_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *InventoryReleaseCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *InventoryReleaseCommand) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type InventoryReleasedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReleasedEvent) Reset() {
	*x = InventoryReleasedEvent{}
	mi := &file_saga_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReleasedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReleasedEvent) ProtoMessage() {}

func (x *InventoryReleasedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReleasedEvent.ProtoReflect.Descriptor instead.
func (*InventoryReleasedEvent) Descriptor() ([]byte, []int) {
	return file_saga_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *InventoryReleasedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type PaymentChargeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentChargeCommand) Reset() {
	*x = PaymentChargeCommand{}
	mi := &file_saga_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentChargeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentChargeCommand) ProtoMessage() {}

func (x *PaymentChargeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentChargeCommand.ProtoReflect.Descriptor instead.
func (*PaymentChargeCommand) Descriptor() ([]byte, []int) {
	return file_saga_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentChargeCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentChargeCommand) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PaymentChargedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentChargedEvent) Reset() {
	*x = PaymentChargedEvent{}
	mi := &file_saga_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentChargedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentChargedEvent) ProtoMessage() {}

func (x *PaymentChargedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentChargedEvent.ProtoReflect.Descriptor instead.
func (*PaymentChargedEvent) Descriptor() ([]byte, []int) {
	return file_saga_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *PaymentChargedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentChargedEvent) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type PaymentFailedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentFailedEvent) Reset() {
	*x = PaymentFailedEvent{}
	mi := &file_saga_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentFailedEvent) ProtoMessage() {}

func (x *PaymentFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentFailedEvent.ProtoReflect.Descriptor instead.
func (*PaymentFailedEvent) Descriptor() ([]byte, []int) {
	return file_saga_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *PaymentFailedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentFailedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type OrderConfirmedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderConfirmedEvent) Reset() {
	*x = OrderConfirmedEvent{}
	mi := &file_saga_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderConfirmedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderConfirmedEvent) ProtoMessage() {}

func (x *OrderConfirmedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderConfirmedEvent.ProtoReflect.Descriptor instead.
func (*OrderConfirmedEvent) Descriptor() ([]byte, []int) {
	return file_saga_v1_events_proto_rawDescGZIP(), []int{11}
}

func (x *OrderConfirmedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type OrderRejectedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRejectedEvent) Reset() {
	*x = OrderRejectedEvent{}
	mi := &file_saga_v1_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRejectedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRejectedEvent) ProtoMessage() {}

func (x *OrderRejectedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_saga_v1_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRejectedEvent.ProtoReflect.Descriptor instead.
func (*OrderRejectedEvent) Descriptor() ([]byte, []int) {
	return file_saga_v1_events_proto_rawDescGZIP(), []int{12}
}

func (x *OrderRejectedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderRejectedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_saga_v1_events_proto protoreflect.FileDescriptor

const file_saga_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x14saga/v1/events.proto\x12\asaga.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x01\n" +
	"\tSagaEvent\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"{\n" +
	"\x11OrderCreatedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.saga.v1.OrderItemR\x05items\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmount\"@\n" +
	"\tOrderItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"^\n" +
	"\x17InventoryReserveCommand\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.saga.v1.OrderItemR\x05items\"3\n" +
	"\x16InventoryReservedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"I\n" +
	"\x14InventoryFailedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"^\n" +
	"\x17InventoryReleaseCommand\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.saga.v1.OrderItemR\x05items\"3\n" +
	"\x16InventoryReleasedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"I\n" +
	"\x14PaymentChargeCommand\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"O\n" +
	"\x13PaymentChargedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\"G\n" +
	"\x12PaymentFailedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"0\n" +
	"\x13OrderConfirmedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"G\n" +
	"\x12OrderRejectedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reasonB<Z:github.com/pavelmaksimov25/go-oms/pkg/proto/saga/v1;sagav1b\x06proto3"

var (
	file_saga_v1_events_proto_rawDescOnce sync.Once
	file_saga_v1_events_proto_rawDescData []byte
)

func file_saga_v1_events_proto_rawDescGZIP() []byte {
	file_saga_v1_events_proto_rawDescOnce.Do(func() {
		file_saga_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saga_v1_events_proto_rawDesc), len(file_saga_v1_events_proto_rawDesc)))
	})
	return file_saga_v1_events_proto_rawDescData
}

var file_saga_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_saga_v1_events_proto_goTypes = []any{
	(*SagaEvent)(nil),               // 0: saga.v1.SagaEvent
	(*OrderCreatedEvent)(nil),       // 1: saga.v1.OrderCreatedEvent
	(*OrderItem)(nil),               // 2: saga.v1.OrderItem
	(*InventoryReserveCommand)(nil), // 3: saga.v1.InventoryReserveCommand
	(*InventoryReservedEvent)(nil),  // 4: saga.v1.InventoryReservedEvent
	(*InventoryFailedEvent)(nil),    // 5: saga.v1.InventoryFailedEvent
	(*InventoryReleaseCommand)(nil), // 6: saga.v1.InventoryReleaseCommand
	(*InventoryReleasedEvent)(nil),  // 7: saga.v1.InventoryReleasedEvent
	(*PaymentChargeCommand)(nil),    // 8: saga.v1.PaymentChargeCommand
	(*PaymentChargedEvent)(nil),     // 9: saga.v1.PaymentChargedEvent
	(*PaymentFailedEvent)(nil),      // 10: saga.v1.PaymentFailedEvent
	(*OrderConfirmedEvent)(nil),     // 11: saga.v1.OrderConfirmedEvent
	(*OrderRejectedEvent)(nil),      // 12: saga.v1.OrderRejectedEvent
	(*timestamppb.Timestamp)(nil),   // 13: google.protobuf.Timestamp
}
var file_saga_v1_events_proto_depIdxs = []int32{
	13, // 0: saga.v1.SagaEvent.created_at:type_name -> google.protobuf.Timestamp
	2,  // 1: saga.v1.OrderCreatedEvent.items:type_name -> saga.v1.OrderItem
	2,  // 2: saga.v1.InventoryReserveCommand.items:type_name -> saga.v1.OrderItem
	2,  // 3: saga.v1.InventoryReleaseCommand.items:type_name -> saga.v1.OrderItem
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_saga_v1_events_proto_init() }
func file_saga_v1_events_proto_init() {
	if File_saga_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saga_v1_events_proto_rawDesc), len(file_saga_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_saga_v1_events_proto_goTypes,
		DependencyIndexes: file_saga_v1_events_proto_depIdxs,
		MessageInfos:      file_saga_v1_events_proto_msgTypes,
	}.Build()
	File_saga_v1_events_proto = out.File
	file_saga_v1_events_proto_goTypes = nil
	file_saga_v1_events_proto_depIdxs = nil
}
