apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: go-oms-inventory:latest
          imagePullPolicy: Never
          ports:
            - name: grpc
              containerPort: 50052
            - name: http
              containerPort: 8080
          env:
            - name: GRPC_PORT
              value: "50052"
            - name: HTTP_PORT
              value: "8080"
            - name: KAFKA_BROKERS
              value: "kafka.oms.svc.cluster.local:9092"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
