apiVersion: apps/v1
kind: Deployment
metadata:
  name: saga-orchestrator
  namespace: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saga-orchestrator
  template:
    metadata:
      labels:
        app: saga-orchestrator
    spec:
      containers:
        - name: saga-orchestrator
          image: go-oms-orchestrator:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: KAFKA_BROKERS
              value: "kafka.oms.svc.cluster.local:9092"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
